### ISSUE TITLE
The user migration parameter doesn’t have it default value as a true.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#1]
Description
In the configuration.properties file of the migrator, the parameter “migrate.users” was left empty. Therefore, this parameter should take the value “true” as default. However, is considered that the parameter took a value of “false” because when the database was cleaned, the information of the users wasn’t deleted.

Steps to reproduce:
1)	In configuration.properties file of the migrator, the value of migrate.users should be empty.
2)	Execute the method of cleanRdapDBTest located in IndividualMigrationProcessTest
3)	Execute the method of migrateUsersTest located in IndividualMigrationProcessTest

**Comment by DAlpuche** [comment]
Current behavior is expected: when the "migrate.users" parameters was left empty the default value will be false, this because it's unlikely that in every migration process the users will be migrated. 

Solution:
Changed the comment in the configuration file, to explain that the default value of "migrate.users" will be "false".
