### ISSUE TITLE
Database access

### ISSUE THREAD

**Issue by batlogs** [NICMx/rdap-server#112]
I am looking to build the database that stores all this information. Any suggestions as to where to start looking into getting bulk IPv4 and IPv6 data?

**Comment by dhfelix** [comment]
Hello, I have a question, are the IPv6 and IPv4 data for 'nameserver' or 'ip_network'?

We currently have 3 options to get the data from RedDog.
They are found in this [**link**](https://www.reddog.mx/documentation.html) as options one, two and three.

I explain quickly:
Option 1: Generate a new Java data access library and use your private database schema. You can implement only the functions you need from the API "rdap-data-access-api".

Option 2: Using our "rdap-sql-provider" library and use your database schema, overwriting our SQL SELECT, to get the information from your database.

option 3: use our library and our database schema. Here it is necessary to export the information from your database to the new database schema that we propose.

We do not have a mechanism to transfer the information since the user databases are different from each other.

We hope that the documentation is useful to you and if you have any questions, do not hesitate to contact us.

**Comment by batlogs** [comment]
Thanks for the response! I am trying to build an API that would go to all the Registries with either IPv4/ IPv6 IP address and then parse the response from each of these as JSON. Hence I wanted to know if the Database that you have built takes data from all the registries  periodically? if so, how did you go about creating this database?

**Comment by dhfelix** [comment]
> Thanks for the response! I am trying to build an API that would go to all the Registries with either IPv4/ IPv6 IP address and then parse the response from each of these as JSON. 

It sounds like an RDAP client. 

> Hence I wanted to know if the Database that you have built takes data from all the registries periodically?

no, our DB doesn't pull data from registries or registrars, the implementer of RedDog (RDAP server) must install the DB in its servers and populate it with its own data

**Comment by batlogs** [comment]
Yes I am trying to build a RDAP client, can I use/modify RedDog code base to make calls to all the registries. If not, do you have any suggestion on any existing RDAP client I could look into?

**Comment by dhfelix** [comment]
Oh I see, now I understand you.

RedDog is intended to be an RDAP server, not an RDAP client.
but yes, you are free to modify RedDog.

~I remember reading a presentation where RDAP clients were mentioned, but I can't find it or maybe it was just my imagination.~

I have never used an RDP client, but I have found these:
https://www.openrdap.org/
https://github.com/metaregistrar/rdap-client
https://about.rdap.org/

**Comment by batlogs** [comment]
Thanks for the list, I am exploring openrdap as an reference. It looks pretty complete in its implementation. I will also evaluate metaregister. Was curious to know if you happen to know any Java based RDAP clients

**Comment by dhfelix** [comment]
Sorry for the delayed response.

I haven't used any RDAP client, to test the RedDog server, I used the web browser and two REST clients, Postman and Insomnia.

As an RDAP server, we care more that the JSON response is well formed and complies with RDAP RFCs, this way RDAP clients can easily interpret the responses from the RDAP server.

**Comment by batlogs** [comment]
ok thanks for your time and appreciate your efforts on RedDog
