### ISSUE TITLE
Object not found when asking for a domain by nsIP parameter with an ipv6

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#23]
When doing a search for a domain using an nsIP parameter with an ipv6, it shown an object not found, even though the object is in the bd.

This is the search that I made when asking for a domain through its nameserver ip with an ipv6
http://localhost:8080/rdap-server/domains?nsIp=1::1

**Comment by dhfelix** [comment]
The server validates the input of the request, that is it, validate that the incoming IP address “1::1” is actually an IP address, and when the server sends the request to the data-access, expands the IP address.

In the demo server we store the address as Strings, and that’s why doesn’t match the expanded IP vs the stored address (1::1), because demo server is not a priority and this bug do not affect the “main” server, the way that I resolve this is store the expanded IPv6 address.
