### ISSUE TITLE
`operational_profile` is useless as presented

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#30]
https://www.reddog.mx/behavior-configuration.html#operational_profile

ICANN's document lists several requirements that _cannot_ be fulfilled by RD on its own. One quick example: 1.3.8: "RDAP services MUST be available over both IPv4 and IPv6 transport."

The `operational_profile` field is **completely useless** if its documentation fails to state what is covered by RD and what needs extra effort. We can't have users enable this switch and assume they are automatically compliant. Are we seriously expecting them to dive into the source code?

I guess what I'm asking for is a table that looks somewhat like this:

| Requirement | registry | registrar | none |
|---|---|---|---|
| 1.2 | ✓ | ✓ | x |
| 1.3 | x | ✓ | x |
| 1.4 | ✓ | Needs extra effort | x |
| ... | ... | ... | ... |

Also, the `none` value is puzzling. Are all the "validations and requirements" disabled when `none` is the active profile? Is there any reason to avoid these requirements like the plague when the user is neither a registry nor a registrar?

**Comment by pcarana** [comment]
The implementation was confusing since the server didn't implemented much of what the Operational Profile states, so it has been removed, it had too much work still to be done (code and documentation) and also could create false expectactions.

The "terms of service" were loaded depending on the operational profile, now they are loaded if the file exists.

**Comment by TheRedTrainer** [comment]
Verified. The operational profile functionality was removed from rdap server. The terms of service are loaded if tos.xml default file is configured.
