### ISSUE TITLE
Default values in privacy configuration are not working.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#5]
**Description**
According to the documentation the default value of privacy is “any”. However, when those values are left empty the server fails to start. The server should not fail to start; it just has to interpret that when there is empty in whichever privacy configuration’s properties means that the value is “any”.
This situation happens with every privacy configuration property located in the privacy_default’s folder.

**Comment by dhfelix** [comment]
The default values are set in the folder "META-INF / privacy_default", it is expected that if any required file is not in the folder, the application fails, since they are files required by the application. The user can overwrite these default values by creating the files in the folder "WEB-INF / privacy".

It is expected that the "src / META-INF" folder will only be modified by developers and not by users.
