### ISSUE TITLE
Invalid partial search error message in domains?nsIp search that doesn't allow partial search

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#58]
If the rdap server has the "allow_search_wildcars_anywhere" property (in configuration.properties) turned off and a client execute a domains search by nsIP like this:

http://localhost:8080/rdap-server/domains?nsIp=*100.0.0.*

The following error message is displayed:

> {"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Partial search can only have wildcards at the end of each label"}

However, the message that should be displayed is : 

> {"rdapConformance":["rdap_level_0"],"errorCode":"400","description":"Invalid IPv4 address : 100.0.0.*"}

because the wildcards are not allowed in domains?nsIP partial search.

**Comment by pcarana** [comment]
The error used to identify the problem was correct (code 422), only the description wasn't completely related to the search made.

Commit 9ed452fbc507171fedb6a2e7b3fd522991b05fff updates the error description to:

"**Partial search can only have a wildcard at the end of each octet/field**"

> However, the message that should be displayed is :
>
>{"rdapConformance":["rdap_level_0"],"errorCode":"400","description":"Invalid IPv4 address : 100.0.0.*"}
>
>because the wildcards are not allowed in domains?nsIP partial search.

This is related to the issue #57, the server isn't the responsible of valid/implemented partial searches, this should be in the implementation; so, the server only validates what it can _(eg. wildcards at the end of the label)_ and the implementation is responsible to indicate that the use of wildcards isn't allowed for IP query params _(eg. domains?nsIp, nameservers?ip)_.

**Comment by TheRedTrainer** [comment]
Verified. When an user executes the following search:

> http://localhost:8080/rdap-server/domains?nsIp=052.176.234.*

the server returns the following error message:

> {"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Partial search using IPs isn't implemented, try another search"}

**Comment by TheRedTrainer** [comment]
Verified. When an user executes a search filtering by IP and using a wildcard at the beginning of the octet/field when "allow_search_wildcars_anywhere" property is setted as "false", the server returns the following error message: 

{"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Partial search can only have a wildcard at the end of each octet/field"}

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
